[Cb]
key = "Cb"
has_flats = true
number_of_accidentals = 7
accidentals = "BEADGCF"
relative_minor = "Ab"

[Gb]
key = "Gb"
has_flats = true
number_of_accidentals = 6
accidentals = "BEADGC"
relative_minor = "Eb"

[Db]
key = "Db"
has_flats = true
number_of_accidentals = 5
accidentals = "BEADG"
relative_minor = "Bb"

[Ab]
key = "Ab"
has_flats = true
number_of_accidentals = 4
accidentals = "BEAD"
relative_minor = "F"

[Eb]
key = "Eb"
has_flats = true
number_of_accidentals = 3
accidentals = "BEA"
relative_minor = "C"

[Bb]
key = "Bb"
has_flats = true
number_of_accidentals = 2
accidentals = "BE"
relative_minor = "G"

[F]
key = "F"
has_flats = true
number_of_accidentals = 1
accidentals = "B"
relative_minor = "D"

[C]
key = "C"
has_flats = false
number_of_accidentals = 0
accidentals = ""
relative_minor = "A"

[G]
key = "G"
has_flats = false
number_of_accidentals = 1
accidentals = "F"
relative_minor = "E"

[D]
key = "D"
has_flats = false
number_of_accidentals = 2
accidentals = "FC"
relative_minor = "B"

[A]
key = "A"
has_flats = false
number_of_accidentals = 3
accidentals = "FCG"
relative_minor = "F#"

[E]
key = "E"
has_flats = false
number_of_accidentals = 4
accidentals = "FCGD"
relative_minor = "C#"

[B]
key = "B"
has_flats = false
number_of_accidentals = 5
accidentals = "FCGDA"
relative_minor = "G#"

["F#"]
key = "F#"
has_flats = false
number_of_accidentals = 6
accidentals = "FCGDAE"
relative_minor = "D#"

["C#"]
key = "C#"
has_flats = false
number_of_accidentals = 7
accidentals = "FCGDAEB"
relative_minor = "A#"
